const MODULE = 'CATEGORIES';

export default {
  GET_CATEGORIES: `${MODULE}/GET_CATEGORIES`,
  GET_CATEGORIES_SUCCESS: `${MODULE}/GET_CATEGORIES_SUCCESS`,
  GET_CATEGORIES_PENDING: `${MODULE}/GET_CATEGORIES_PENDING`,
  GET_CATEGORIES_REJECTED: `${MODULE}/GET_CATEGORIES_REJECTED`,
};
