const MODULE = 'ITEMS';

export default {
  GET_ITEMS: `${MODULE}/GET_ITEMS`,
  GET_ITEMS_SUCCESS: `${MODULE}/GET_ITEMS_SUCCESS`,
  GET_ITEMS_PENDING: `${MODULE}/GET_ITEMS_PENDING`,
  GET_ITEMS_REJECTED: `${MODULE}/GET_ITEMS_REJECTED`,
};
